# ===========================================
# DOCKER COMPOSE - BACKEND SIMPLES
# ===========================================

services:
  # ===========================================
  # BACKEND API SIMPLES
  # ===========================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pleasuregame_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3333
      JWT_SECRET: pleasuregame-secret-key-super-secure-2024-production
      DATABASE_URL: "postgresql://postgres:15951522@pleasuregame_db:5432/pleasuregame_db"
      WEBHOOK_SECRET: your-webhook-secret-key
      WEBHOOK_TOKEN: ad7e97a7b9af490c8b596feddd055350
      WEBHOOK_TIMEOUT: 300
    ports:
      - "${BACKEND_PORT:-3333}:3333"
    networks:
      - backend_pleasuregame_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

# ===========================================
# VOLUMES PERSISTENTES
# ===========================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# ===========================================
# REDE PERSONALIZADA
# ===========================================
networks:
  backend_pleasuregame_network:
    external: true 